// لیست سایت‌های آموزشی معتبر ایرانی - آدرس‌ها بررسی و اصلاح شده
// + ۲۰ دانشگاه معتبر ایرانی + رتبه‌بندی

export interface ResourceSite {
  id: string
  name: string
  url: string
  description: string
  category: 'video' | 'answer' | 'practice' | 'other'
  subjects: string[]
  emoji: string
  isFree: boolean
}

export const RESOURCE_SITES: ResourceSite[] = [
  // ===== سایت‌های ویدئویی آموزشی =====
  {
    id: 'maz',
    name: 'مآز',
    url: 'https://www.maz.ir',
    description: 'پلتفرم آموزش ویدئویی با هزاران دوره آموزشی در زمینه‌های مختلف تحصیلی، کنکور و دانشگاهی. ویدئوهای باکیفیت از بهترین اساتید.',
    category: 'video',
    subjects: ['کنکور', 'دبیرستان', 'دانشگاه'],
    emoji: '🎬',
    isFree: false,
  },
  {
    id: 'ala',
    name: 'آلاء',
    url: 'https://alaatv.com',
    description: 'پلتفرم آموزشی آلاء با ویدئوهای آموزشی رایگان و پولی برای مقاطع مختلف تحصیلی. یکی از قدیمی‌ترین سایت‌های آموزش ویدئویی.',
    category: 'video',
    subjects: ['کنکور', 'دبیرستان', 'راهنمایی'],
    emoji: '🎥',
    isFree: true,
  },
  {
    id: 'mktb',
    name: 'مکتب‌خونه',
    url: 'https://www.maktabkhooneh.org',
    description: 'پلتفرم آموزش آنلاین با دوره‌های دانشگاهی و تخصصی. همکاری با دانشگاه‌های معتبر ایران و ارائه دوره‌های رایگان و پولی.',
    category: 'video',
    subjects: ['دانشگاه', 'تخصصی'],
    emoji: '🏫',
    isFree: true,
  },
  {
    id: 'frd',
    name: 'فرادرس',
    url: 'https://faradars.org',
    description: 'بزرگترین پلتفرم آموزش ویدئویی ایران با هزاران دوره در زمینه‌های مختلف از برنامه‌نویسی و طراحی تا کنکور و زبان.',
    category: 'video',
    subjects: ['برنامه‌نویسی', 'طراحی', 'کنکور', 'زبان'],
    emoji: '📹',
    isFree: false,
  },
  {
    id: 'ostad',
    name: 'استادبانک',
    url: 'https://ostadbank.com',
    description: 'پلتفرم آموزشی ویدئویی با دوره‌های کنکور و دبیرستان. امکان مشاهده اولین جلسه هر دوره به صورت رایگان.',
    category: 'video',
    subjects: ['کنکور', 'دبیرستان'],
    emoji: '👨‍🏫',
    isFree: false,
  },
  {
    id: 'aparat',
    name: 'آپارات',
    url: 'https://www.aparat.com',
    description: 'بزرگترین سایت اشتراک ویدئو ایران با هزاران ویدئوی آموزشی در تمامی موضوعات. کانال‌های آموزشی اساتید معروف.',
    category: 'video',
    subjects: ['عمومی', 'کنکور', 'دانشگاه'],
    emoji: '📺',
    isFree: true,
  },
  {
    id: 'filimo',
    name: 'فیلیمو',
    url: 'https://www.filimo.com',
    description: 'پلتفرم استریم ویدئو ایران با بخش آموزشی گسترده. شامل دوره‌های آموزشی، مستند و فیلم‌های آموزشی.',
    category: 'video',
    subjects: ['عمومی', 'مستند'],
    emoji: '🎞️',
    isFree: false,
  },
  {
    id: 'fidibo',
    name: 'فیدیبو',
    url: 'https://www.fidibo.com',
    description: 'پلتفرم کتابخوان و آموزشی با صوت کتاب، کتاب الکترونیک و دوره‌های آموزشی در موضوعات مختلف.',
    category: 'video',
    subjects: ['کتاب', 'صوتی', 'عمومی'],
    emoji: '📚',
    isFree: false,
  },
  {
    id: 'kanoon',
    name: 'موسسه ثبت',
    url: 'https://www.kanoon.ir',
    description: 'سایت موسسه آموزشی ثبت با ویدئوهای آموزشی، آزمون‌های آزمایشی و منابع کنکور برای تمامی پایه‌ها.',
    category: 'video',
    subjects: ['کنکور', 'دبیرستان'],
    emoji: '🎯',
    isFree: false,
  },
  {
    id: 'sebtar',
    name: 'سیب ترش',
    url: 'https://www.sebtar.com',
    description: 'سامانه آموزش ویدئویی سیب ترش با دوره‌های تخصصی کنکور و دبیرستان. ویدئوهای تدریس اساتید برتر به صورت فصل به فصل.',
    category: 'video',
    subjects: ['کنکور', 'دبیرستان'],
    emoji: '🍎',
    isFree: false,
  },
  {
    id: 'darsnameh',
    name: 'درس‌نامه',
    url: 'https://www.darsnameh.com',
    description: 'پلتفرم آموزش آنلاین با ویدئوهای آموزشی درسی برای پایه‌های مختلف. مناسب دانش‌آموزان ابتدایی تا دبیرستان.',
    category: 'video',
    subjects: ['ابتدایی', 'راهنمایی', 'دبیرستان'],
    emoji: '📖',
    isFree: false,
  },
  {
    id: 'takbook',
    name: 'تک‌بوک',
    url: 'https://www.takbook.com',
    description: 'سایت آموزشی با ویدئوهای آموزشی، کتاب الکترونیک و منابع درسی برای کنکور و دبیرستان.',
    category: 'video',
    subjects: ['کنکور', 'دبیرستان'],
    emoji: '📕',
    isFree: true,
  },

  // ===== سایت‌های جواب کتاب =====
  {
    id: 'magerta',
    name: 'ماگرتا',
    url: 'https://magerta.ir',
    description: 'مرجع کامل پاسخنامه کتاب‌های درسی ایران. جواب تمامی کتاب‌های مدرسه از ابتدایی تا پیش‌دانشگاهی با توضیح کامل.',
    category: 'answer',
    subjects: ['دبیرستان', 'راهنمایی', 'ابتدایی'],
    emoji: '📚',
    isFree: true,
  },
  {
    id: 'gama',
    name: 'گاما',
    url: 'https://gama.ir',
    description: 'پلتفرم آموزشی با پاسخنامه کتاب‌های درسی، ویدئوهای آموزشی و آزمون آنلاین. مرجع کامل دانش‌آموزان ایرانی.',
    category: 'answer',
    subjects: ['دبیرستان', 'کنکور'],
    emoji: '🎯',
    isFree: true,
  },
  {
    id: 'padars',
    name: 'پادرس',
    url: 'https://padars.com',
    description: 'سامانه پاسخنامه کتاب‌های درسی با جواب‌نویسی مرحله به مرحله. مناسب دانش‌آموزان مقاطع متوسطه و ثانویه.',
    category: 'answer',
    subjects: ['دبیرستان', 'راهنمایی'],
    emoji: '✏️',
    isFree: true,
  },
  {
    id: 'gam_ir',
    name: 'گام‌آموز',
    url: 'https://www.gam.ir',
    description: 'سایت آموزشی با پاسخنامه و حل تمرین کتاب‌های درسی، ویدئوهای آموزشی و آزمون آنلاین.',
    category: 'answer',
    subjects: ['دبیرستان', 'راهنمایی'],
    emoji: '📝',
    isFree: true,
  },
  {
    id: 'kelidestan',
    name: 'کلیدستان',
    url: 'https://www.kelidestan.com',
    description: 'سایت آموزشی با پاسخنامه کتاب‌های درسی، جزوات آموزشی و منابع کنکور برای تمامی پایه‌ها.',
    category: 'answer',
    subjects: ['دبیرستان', 'کنکور', 'راهنمایی'],
    emoji: '🔑',
    isFree: true,
  },
  {
    id: 'khakdansh',
    name: 'خاک‌دانش',
    url: 'https://khakdansh.ir',
    description: 'سایت آموزشی با پاسخنامه و حل تمرین کتاب‌های درسی. مناسب برای تمرین و مرور دروس مختلف.',
    category: 'answer',
    subjects: ['دبیرستان', 'راهنمایی'],
    emoji: '📖',
    isFree: true,
  },
  {
    id: 'didbook',
    name: 'دیدبوک',
    url: 'https://www.didbook.ir',
    description: 'پلتفرم آموزشی با پاسخنامه کتاب‌های درسی، ویدئوهای آموزشی و منابع کنکور برای دانش‌آموزان.',
    category: 'answer',
    subjects: ['دبیرستان', 'کنکور'],
    emoji: '👀',
    isFree: true,
  },
  {
    id: 'daneshjooyar',
    name: 'دانشجویار',
    url: 'https://www.daneshjooyar.ir',
    description: 'سایت آموزشی با پاسخنامه کتاب‌های درسی دانشگاهی و دبیرستانی، جزوات و منابع آموزشی.',
    category: 'answer',
    subjects: ['دانشگاه', 'دبیرستان'],
    emoji: '🎓',
    isFree: true,
  },
  {
    id: 'talkisho',
    name: 'تالکیشو',
    url: 'https://www.talkisho.com',
    description: 'سایت آموزشی با پاسخنامه کتاب‌های درسی و منابع کنکور. مناسب برای دانش‌آموزان دبیرستانی.',
    category: 'answer',
    subjects: ['دبیرستان', 'کنکور'],
    emoji: '💬',
    isFree: true,
  },
  {
    id: 'persianv',
    name: 'پرشین‌وی',
    url: 'https://www.persianv.com',
    description: 'پلتفرم آموزشی با پاسخنامه کتاب‌های درسی، ویدئوهای آموزشی و منابع کنکور.',
    category: 'answer',
    subjects: ['دبیرستان', 'کنکور'],
    emoji: '🇮🇷',
    isFree: true,
  },

  // ===== سایت‌های آزمون و تمرین =====
  {
    id: 'sanjesh',
    name: 'سازمان سنجش',
    url: 'https://www.sanjesh.org',
    description: 'سایت رسمی سازمان سنجش برای ثبت‌نام و نتایج آزمون‌های سراسری کنکور و سایر آزمون‌های ملی.',
    category: 'practice',
    subjects: ['کنکور', 'آزمون ملی'],
    emoji: '📊',
    isFree: true,
  },
  {
    id: 'mehrin',
    name: 'مهرین',
    url: 'https://mehrin.com',
    description: 'پلتفرم آزمون آنلاین با آزمون‌های آزمایشی کنکور، بررسی نقاط ضعف و نقاط قوی، و گزارش تحلیلی کامل.',
    category: 'practice',
    subjects: ['کنکور'],
    emoji: '📝',
    isFree: false,
  },
  {
    id: 'mirath',
    name: 'میراث',
    url: 'https://mirath.ir',
    description: 'سایت آزمون‌های آزمایشی آنلاین با تحلیل عملکرد و رتبه‌بندی. مناسب برای آمادگی کنکور.',
    category: 'practice',
    subjects: ['کنکور'],
    emoji: '🥇',
    isFree: false,
  },
  {
    id: 'konkur1',
    name: 'کنکور',
    url: 'https://www.konkur.ir',
    description: 'سایت تخصصی کنکور با آزمون‌های آزمایشی، منابع آموزشی و مشاوره تحصیلی برای داوطلبان.',
    category: 'practice',
    subjects: ['کنکور'],
    emoji: '🎯',
    isFree: false,
  },
  {
    id: 'kelaskonkur',
    name: 'کلاس کنکور',
    url: 'https://www.kelaskonkur.ir',
    description: 'پلتفرم آموزشی و آزمون آنلاین مخصوص کنکور با آزمون‌های آزمایشی و تحلیل رتبه.',
    category: 'practice',
    subjects: ['کنکور'],
    emoji: '🏫',
    isFree: false,
  },
  {
    id: 'masterkonkur',
    name: 'مستر کنکور',
    url: 'https://www.masterkonkur.ir',
    description: 'سایت آزمون‌های آزمایشی کنکور با رتبه‌بندی، تحلیل عملکرد و منابع آموزشی.',
    category: 'practice',
    subjects: ['کنکور'],
    emoji: '🏅',
    isFree: false,
  },
  {
    id: 'sana',
    name: 'سامانه سنا',
    url: 'https://www.sana.ir',
    description: 'سامانه آموزشی و آزمون آنلاین با آزمون‌های آزمایشی و منابع آموزشی برای کنکور.',
    category: 'practice',
    subjects: ['کنکور', 'دبیرستان'],
    emoji: '💻',
    isFree: false,
  },

  // ===== سایت‌های مفید آموزشی =====
  {
    id: 'roshd',
    name: 'پایگاه آموزشی رشد',
    url: 'https://www.roshd.ir',
    description: 'پایگاه رسمی آموزش و پرورش با منابع آموزشی، ویدئوهای درسی و مطالب کمک‌آموزشی برای تمامی مقاطع.',
    category: 'other',
    subjects: ['ابتدایی', 'راهنمایی', 'دبیرستان'],
    emoji: '🌱',
    isFree: true,
  },
  {
    id: 'medu',
    name: 'وزارت آموزش و پرورش',
    url: 'https://medu.ir',
    description: 'سایت رسمی وزارت آموزش و پرورش با اطلاعیه‌ها، منابع آموزشی و سامانه‌های مرتبط.',
    category: 'other',
    subjects: ['ابتدایی', 'راهنمایی', 'دبیرستان'],
    emoji: '🏛️',
    isFree: true,
  },
  {
    id: 'sharif',
    name: 'دانشگاه شریف',
    url: 'https://www.sharif.edu',
    description: 'سایت رسمی دانشگاه شریف با منابع آموزشی، اخبار و رویدادهای علمی. مناسب برای دانشجویان و داوطلبان کنکور.',
    category: 'other',
    subjects: ['دانشگاه', 'کنکور'],
    emoji: '🎓',
    isFree: true,
  },
  {
    id: 'schools_medu',
    name: 'سامانه مدارس',
    url: 'https://schools.medu.ir',
    description: 'سامانه مدارس وزارت آموزش و پرورش برای ثبت‌نام، نمرات و اطلاع‌رسانی‌های مدارس.',
    category: 'other',
    subjects: ['ابتدایی', 'راهنمایی', 'دبیرستان'],
    emoji: '🏫',
    isFree: true,
  },
  {
    id: 'mehrnews',
    name: 'خبرگزاری مهر',
    url: 'https://www.mehrnews.com',
    description: 'خبرگزاری مهر با بخش آموزشی، اخبار کنکور، دانشگاه‌ها و تحلیل‌های آموزشی.',
    category: 'other',
    subjects: ['کنکور', 'دانشگاه', 'اخبار'],
    emoji: '📰',
    isFree: true,
  },
  {
    id: 'amuzesh',
    name: 'پایگاه آموزش',
    url: 'https://www.amuzesh.ir',
    description: 'پایگاه آموزشی با منابع آموزشی، ویدئوهای درسی و مطالب کمک‌آموزشی برای دانش‌آموزان.',
    category: 'other',
    subjects: ['ابتدایی', 'راهنمایی', 'دبیرستان'],
    emoji: '📚',
    isFree: true,
  },
  {
    id: 'dars_ir',
    name: 'درس',
    url: 'https://www.dars.ir',
    description: 'سایت آموزشی با ویدئوهای درسی، آزمون آنلاین و منابع آموزشی برای تمامی مقاطع.',
    category: 'other',
    subjects: ['ابتدایی', 'راهنمایی', 'دبیرستان'],
    emoji: '✏️',
    isFree: true,
  },
  {
    id: 'encyclopedia',
    name: 'دانشنامه',
    url: 'https://www.encyclopedia.ir',
    description: 'دانشنامه آنلاین ایرانی با مقالات آموزشی در زمینه‌های مختلف علمی، ادبی و تاریخی.',
    category: 'other',
    subjects: ['عمومی', 'دانشگاه'],
    emoji: '📖',
    isFree: true,
  },
  {
    id: 'khaandani',
    name: 'خواندنی‌ها',
    url: 'https://www.khaandani.ir',
    description: 'سایت مطالب خواندنی و آموزشی با مقالات متنوع در زمینه‌های علمی، تاریخی و فرهنگی.',
    category: 'other',
    subjects: ['عمومی'],
    emoji: '📜',
    isFree: true,
  },
  {
    id: 'irantracks',
    name: 'ایران‌تراکس',
    url: 'https://www.irantracks.com',
    description: 'سایت آموزشی و دانلود منابع درسی، جزوات و ویدئوهای آموزشی برای کنکور و دبیرستان.',
    category: 'other',
    subjects: ['کنکور', 'دبیرستان'],
    emoji: '🎯',
    isFree: true,
  },
  {
    id: 'talar',
    name: 'تالار',
    url: 'https://www.talar.id',
    description: 'پلتفرم آموزشی و اجتماعی با ویدئوهای آموزشی، وبینار و دوره‌های تخصصی.',
    category: 'other',
    subjects: ['دانشگاه', 'تخصصی'],
    emoji: '🎤',
    isFree: false,
  },
  {
    id: 'ghadeedeasr',
    name: 'قضای عصر',
    url: 'https://www.ghadeedeasr.ir',
    description: 'سایت آموزشی و فرهنگی با مقالات، ویدئوهای آموزشی و منابع درسی.',
    category: 'other',
    subjects: ['عمومی', 'دبیرستان'],
    emoji: '⏰',
    isFree: true,
  },
  
  // ===== ۲۰ دانشگاه معتبر ایرانی =====
  {
    id: 'ut',
    name: 'دانشگاه تهران',
    url: 'https://www.ut.ac.ir',
    description: 'قدیمی‌ترین و معتبرترین دانشگاه ایران. دانشگاه مادر کشور با رتبه اول در بسیاری از رشته‌ها.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🏛️',
    isFree: true,
  },
  {
    id: 'sharif_uni',
    name: 'دانشگاه شریف',
    url: 'https://www.sharif.edu',
    description: 'برترین دانشگاه مهندسی ایران. معتبرترین مدرک مهندسی و علوم پایه.',
    category: 'other',
    subjects: ['دانشگاه', 'مهندسی'],
    emoji: '⚙️',
    isFree: true,
  },
  {
    id: 'aut',
    name: 'دانشگاه امیرکبیر',
    url: 'https://www.aut.ac.ir',
    description: 'دانشگاه تکنولوژی امیرکبیر - یکی از معتبرترین دانشگاه‌های مهندسی تهران.',
    category: 'other',
    subjects: ['دانشگاه', 'مهندسی'],
    emoji: '🔧',
    isFree: true,
  },
  {
    id: 'sku',
    name: 'دانشگاه شهید بهشتی',
    url: 'https://www.sbu.ac.ir',
    description: 'دانشگاه شهید بهشتی - معتبر در رشته‌های علوم انسانی، حقوق و مدیریت.',
    category: 'other',
    subjects: ['دانشگاه', 'علوم انسانی'],
    emoji: '📚',
    isFree: true,
  },
  {
    id: 'ferdowsi',
    name: 'دانشگاه فردوسی مشهد',
    url: 'https://www.ferdowsi.um.ac.ir',
    description: 'یکی از بزرگترین و معتبرترین دانشگاه‌های ایران. برتر در منطقه شرق کشور.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🌅',
    isFree: true,
  },
  {
    id: 'tabrizu',
    name: 'دانشگاه تبریز',
    url: 'https://www.tabrizu.ac.ir',
    description: 'قدیمی‌ترین دانشگاه منطقه شمال غرب. معتبر در رشته‌های مختلف.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🏔️',
    isFree: true,
  },
  {
    id: 'iust',
    name: 'دانشگاه علم و صنعت',
    url: 'https://www.iust.ac.ir',
    description: 'دانشگاه علم و صنعت ایران - تخصصی در مهندسی و فناوری.',
    category: 'other',
    subjects: ['دانشگاه', 'مهندسی'],
    emoji: '🏭',
    isFree: true,
  },
  {
    id: 'khuisf',
    name: 'دانشگاه خوارزمی',
    url: 'https://www.khuisf.ac.ir',
    description: 'دانشگاه خوارزمی - معتبر در علوم تربیتی و روان‌شناسی.',
    category: 'other',
    subjects: ['دانشگاه', 'علوم انسانی'],
    emoji: '🎓',
    isFree: true,
  },
  {
    id: 'umz',
    name: 'دانشگاه مازندران',
    url: 'https://www.umz.ac.ir',
    description: 'دانشگاه مازندران - بزرگترین دانشگاه شمال کشور.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🌊',
    isFree: true,
  },
  {
    id: 'guilan',
    name: 'دانشگاه گیلان',
    url: 'https://www.guilan.ac.ir',
    description: 'دانشگاه گیلان - معتبر در منطقه شمال.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🌳',
    isFree: true,
  },
  {
    id: 'um',
    name: 'دانشگاه اصفهان',
    url: 'https://www.ui.ac.ir',
    description: 'دانشگاه اصفهان - یکی از قدیمی‌ترین و معتبرترین دانشگاه‌های ایران.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🌷',
    isFree: true,
  },
  {
    id: 'znu',
    name: 'دانشگاه زنجان',
    url: 'https://www.znu.ac.ir',
    description: 'دانشگاه زنجان - در حال رشد و توسعه.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '🏞️',
    isFree: true,
  },
  {
    id: 'basu',
    name: 'دانشگاه بوعلی سینا',
    url: 'https://www.basu.ac.ir',
    description: 'دانشگاه بوعلی سینا همدان - معتبر در منطقه غرب.',
    category: 'other',
    subjects: ['دانشگاه'],
    emoji: '⚕️',
    isFree: true,
  },
  {
    id: 'put',
    name: 'دانشگاه صنعتی امیرکبیر',
    url: 'https://www.put.ac.ir',
    description: 'پلی‌تکنیک تهران - تخصصی در مهندسی و تکنولوژی.',
    category: 'other',
    subjects: ['دانشگاه', 'مهندسی'],
    emoji: '🏗️',
    isFree: true,
  },
  {
    id: 'iut',
    name: 'دانشگاه صنعتی اصفهان',
    url: 'https://www.iut.ac.ir',
    description: 'دانشگاه صنعتی اصفهان - معتبر در مهندسی و کشاورزی.',
    category: 'other',
    subjects: ['دانشگاه', 'مهندسی'],
    emoji: '🚜',
    isFree: true,
  },
  {
    id: 'mui',
    name: 'دانشگاه علوم پزشکی اصفهان',
    url: 'https://www.mui.ac.ir',
    description: 'دانشگاه علوم پزشکی اصفهان - معتبر در پزشکی و علوم پزشکی.',
    category: 'other',
    subjects: ['دانشگاه', 'پزشکی'],
    emoji: '🏥',
    isFree: true,
  },
  {
    id: 'kmu',
    name: 'دانشگاه علوم پزشکی کرمان',
    url: 'https://www.kmu.ac.ir',
    description: 'دانشگاه علوم پزشکی کرمان - معتبر در منطقه جنوب شرقی.',
    category: 'other',
    subjects: ['دانشگاه', 'پزشکی'],
    emoji: '💊',
    isFree: true,
  },
  {
    id: 'tums',
    name: 'دانشگاه علوم پزشکی تهران',
    url: 'https://www.tums.ac.ir',
    description: 'دانشگاه علوم پزشکی تهران - برترین دانشگاه پزشکی ایران.',
    category: 'other',
    subjects: ['دانشگاه', 'پزشکی'],
    emoji: '🩺',
    isFree: true,
  },
  {
    id: 'sbmu',
    name: 'دانشگاه علوم پزشکی شهید بهشتی',
    url: 'https://www.sbmu.ac.ir',
    description: 'دانشگاه علوم پزشکی شهید بهشتی - یکی از معتبرترین دانشگاه‌های پزشکی.',
    category: 'other',
    subjects: ['دانشگاه', 'پزشکی'],
    emoji: '⚕️',
    isFree: true,
  },
  {
    id: 'msh',
    name: 'دانشگاه مشهد علوم پزشکی',
    url: 'https://www.mums.ac.ir',
    description: 'دانشگاه علوم پزشکی مشهد - معتبر در پزشکی و خدمات درمانی.',
    category: 'other',
    subjects: ['دانشگاه', 'پزشکی'],
    emoji: '🧬',
    isFree: true,
  },
]

// رتبه‌بندی دانشگاه‌های ایران (بر اساس معروفیت، کیفیت و مقبولیت مدرک)
export interface UniversityRanking {
  rank: number
  name: string
  emoji: string
  score: number // 0 تا 100
  city: string
  specialties: string
  description: string
}

export const UNIVERSITY_RANKINGS: UniversityRanking[] = [
  {
    rank: 1,
    name: 'دانشگاه شریف',
    emoji: '⚙️',
    score: 98,
    city: 'تهران',
    specialties: 'مهندسی، علوم پایه',
    description: 'برترین دانشگاه مهندسی ایران. مدرک آن بالاترین مقبولیت در بازار کار.',
  },
  {
    rank: 2,
    name: 'دانشگاه تهران',
    emoji: '🏛️',
    score: 95,
    city: 'تهران',
    specialties: 'همه رشته‌ها',
    description: 'قدیمی‌ترین و معتبرترین دانشگاه ایران. دانشگاه مادر کشور.',
  },
  {
    rank: 3,
    name: 'دانشگاه امیرکبیر (پلی‌تکنیک)',
    emoji: '🔧',
    score: 92,
    city: 'تهران',
    specialties: 'مهندسی',
    description: 'یکی از معتبرترین دانشگاه‌های مهندسی ایران.',
  },
  {
    rank: 4,
    name: 'دانشگاه علوم پزشکی تهران',
    emoji: '🩺',
    score: 91,
    city: 'تهران',
    specialties: 'پزشکی، داروسازی',
    description: 'برترین دانشگاه علوم پزشکی ایران.',
  },
  {
    rank: 5,
    name: 'دانشگاه فردوسی مشهد',
    emoji: '🌅',
    score: 89,
    city: 'مشهد',
    specialties: 'همه رشته‌ها',
    description: 'یکی از بزرگترین و معتبرترین دانشگاه‌های ایران.',
  },
  {
    rank: 6,
    name: 'دانشگاه شهید بهشتی',
    emoji: '📚',
    score: 88,
    city: 'تهران',
    specialties: 'علوم انسانی، حقوق، مدیریت',
    description: 'معتبر در علوم انسانی و حقوق.',
  },
  {
    rank: 7,
    name: 'دانشگاه علم و صنعت',
    emoji: '🏭',
    score: 86,
    city: 'تهران',
    specialties: 'مهندسی، تکنولوژی',
    description: 'تخصصی در مهندسی و فناوری.',
  },
  {
    rank: 8,
    name: 'دانشگاه تبریز',
    emoji: '🏔️',
    score: 84,
    city: 'تبریز',
    specialties: 'همه رشته‌ها',
    description: 'قدیمی‌ترین دانشگاه منطقه شمال غرب.',
  },
  {
    rank: 9,
    name: 'دانشگاه اصفهان',
    emoji: '🌷',
    score: 83,
    city: 'اصفهان',
    specialties: 'همه رشته‌ها',
    description: 'یکی از قدیمی‌ترین و معتبرترین دانشگاه‌های ایران.',
  },
  {
    rank: 10,
    name: 'دانشگاه صنعتی اصفهان',
    emoji: '🚜',
    score: 82,
    city: 'اصفهان',
    specialties: 'مهندسی، کشاورزی',
    description: 'معتبر در مهندسی و کشاورزی.',
  },
  {
    rank: 11,
    name: 'دانشگاه علوم پزشکی شهید بهشتی',
    emoji: '⚕️',
    score: 81,
    city: 'تهران',
    specialties: 'پزشکی',
    description: 'یکی از معتبرترین دانشگاه‌های علوم پزشکی.',
  },
  {
    rank: 12,
    name: 'دانشگاه گیلان',
    emoji: '🌳',
    score: 79,
    city: 'رشت',
    specialties: 'همه رشته‌ها',
    description: 'معتبر در منطقه شمال کشور.',
  },
  {
    rank: 13,
    name: 'دانشگاه مازندران',
    emoji: '🌊',
    score: 78,
    city: 'بابلسر',
    specialties: 'همه رشته‌ها',
    description: 'بزرگترین دانشگاه شمال کشور.',
  },
  {
    rank: 14,
    name: 'دانشگاه خوارزمی',
    emoji: '🎓',
    score: 77,
    city: 'تهران',
    specialties: 'علوم تربیتی، روان‌شناسی',
    description: 'معتبر در علوم تربیتی و روان‌شناسی.',
  },
  {
    rank: 15,
    name: 'دانشگاه بوعلی سینا',
    emoji: '⚕️',
    score: 75,
    city: 'همدان',
    specialties: 'همه رشته‌ها',
    description: 'معتبر در منطقه غرب کشور.',
  },
]

export const CATEGORY_LABELS: Record<ResourceSite['category'], string> = {
  video: 'سایت‌های ویدئویی',
  answer: 'سایت‌های جواب کتاب',
  practice: 'سایت‌های آزمون و تمرین',
  other: 'سایت‌های مفید',
}

export const CATEGORY_EMOJIS: Record<ResourceSite['category'], string> = {
  video: '🎬',
  answer: '📚',
  practice: '📝',
  other: '🌟',
}
